// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace M.Resolver {
  public static partial class resolver
  {
    static readonly string __ServiceName = "m.resolver.resolver";

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::M.Resolver.IpsResponse> __Marshaller_m_resolver_IpsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::M.Resolver.IpsResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::M.Resolver.IpsResponse> __Method_FirstMethod = new grpc::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::M.Resolver.IpsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FirstMethod",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_m_resolver_IpsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::M.Resolver.ApiReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of resolver</summary>
    public abstract partial class resolverBase
    {
      public virtual global::System.Threading.Tasks.Task<global::M.Resolver.IpsResponse> FirstMethod(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for resolver</summary>
    public partial class resolverClient : grpc::ClientBase<resolverClient>
    {
      /// <summary>Creates a new client for resolver</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public resolverClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for resolver that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public resolverClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected resolverClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected resolverClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::M.Resolver.IpsResponse FirstMethod(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FirstMethod(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::M.Resolver.IpsResponse FirstMethod(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FirstMethod, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::M.Resolver.IpsResponse> FirstMethodAsync(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FirstMethodAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::M.Resolver.IpsResponse> FirstMethodAsync(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FirstMethod, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override resolverClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new resolverClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(resolverBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_FirstMethod, serviceImpl.FirstMethod).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, resolverBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_FirstMethod, serviceImpl.FirstMethod);
    }

  }
}
#endregion
